package ;

import hant.Log;
import hant.FlashDevelopProject;
import orm.Db;

class OrmGenerator
{
	var log : Log;
	var project : FlashDevelopProject;
	
	public function new(log:Log, project:FlashDevelopProject)
    {
		this.log = log;
		this.project = project;
	}
	
	public function generate(db:Db)
	{
		var tables = new Array<OrmTable>();
		
		for (tableName in db.connection.getTables())
        {
			var table = new OrmTable(tableName);
			OrmModelGenerator.make(log, project, db, table.tableName, table.customModelClassName, table.autogenModelClassName, table.customManagerClassName);
			OrmManagerGenerator.make(log, project, db, table.tableName, table.customModelClassName, table.customManagerClassName, table.autogenManagerClassName);
			tables.push(table);
        }
		
		OrmOrmGenerator.make(log, project, tables, "models.server.Orm", "models.server.autogenerated.Orm");
    }
}
